[package]
name = "downstage"
version = "0.1.0"
edition = "2024"

[dependencies]
webdriverbidi = "0.2.2"
tokio = { version = "1.48.0", features = ["full"] }
derive_more = { version = "2.0.1", features = ["debug"] }
